
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\masak\Documents\pomodoro\view\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("500x300")
window.configure(bg = "#F2F1DC")


canvas = Canvas(
    window,
    bg = "#F2F1DC",
    height = 300,
    width = 500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    391.0,
    39.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=319.0,
    y=24.0,
    width=144.0,
    height=29.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    392.0,
    101.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=320.0,
    y=86.0,
    width=144.0,
    height=29.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    391.0,
    164.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=319.0,
    y=149.0,
    width=144.0,
    height=29.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    83.0,
    149.0,
    image=image_image_1
)

canvas.create_text(
    161.0,
    23.0,
    anchor="nw",
    text="作業時間",
    fill="#222222",
    font=("x12y12pxMaruMinya", 20 * -1)
)

canvas.create_rectangle(
    161.0,
    62.0,
    480.0,
    65.0,
    fill="#BF3939",
    outline="")

canvas.create_text(
    161.0,
    85.0,
    anchor="nw",
    text="休憩時間（短）",
    fill="#222222",
    font=("x12y12pxMaruMinya", 20 * -1)
)

canvas.create_rectangle(
    161.0,
    124.0,
    463.0,
    127.0,
    fill="#4E6BED",
    outline="")

canvas.create_text(
    161.0,
    147.0,
    anchor="nw",
    text="休憩時間（長）",
    fill="#222222",
    font=("x12y12pxMaruMinya", 20 * -1)
)

canvas.create_rectangle(
    161.0,
    186.0,
    480.0,
    189.0,
    fill="#4E6BED",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=340.0,
    y=215.0,
    width=140.0,
    height=57.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=166.0,
    y=221.0,
    width=108.07017517089844,
    height=44.0
)
window.resizable(False, False)
window.mainloop()
